# Generated by Django 5.0.1 on 2024-02-27 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('ide', models.IntegerField()),
                ('collage_name', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis', models.CharField(max_length=90)),
                ('sub', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.registering')),
            ],
        ),
    ]
