# Generated by Django 5.0.1 on 2024-02-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
